# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b857df5edb7907d8c1600504edabad7ba5d113f3da7a2efefc2040bbd2fc8783ce2e2f1da5a62c8c8fb1982d22b69c416256fe558b5cd6e78713269fb52c4f

test:
  secret_key_base: 4d6a9adb3e855dfdb5f2f59df2bd07613455a919312e0ace4341ea81f754e50d0c173ce81d971a377784fb17077cad32d09a9e484acba97b9fabeade30af9930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
